pipeline {
    agent none
    stages {
        stage ('Build') {
            agent {
                docker { image 'python:alpine3.19' }
            }
            steps {
                sh 'python -m py_compile App-Python/sources/add2vals.py App-Python/sources/calc.py'
            }
        }
    }
}