pipeline {
    agent none
    stages {
        stage ('Build') {
            agent {
                docker { image 'python:alpine3.19' }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage ('Test') {
            agent {
                docker { image 'qnib/pytest' }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage ('Delivery') {
            agent {
                docker { 
                    image 'six8/pyinstaller-alpine'
                }
            }
            steps {
                sh 'pyinstaller --noconfirm --onefile --log-level DEBUG --clean sources/add2vals.spec'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}